# Generated by Django 5.2.7 on 2025-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('TeamLeader', 'Team Leader'), ('Employee', 'Employee')], default='Employee', max_length=40),
        ),
    ]
